# Generated by Django 5.1.5 on 2025-01-15 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cdd',
            options={'verbose_name': 'CDD'},
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora'},
        ),
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'verbose_name': 'empréstimo', 'verbose_name_plural': 'empréstimos'},
        ),
        migrations.AlterModelOptions(
            name='livrotemautor',
            options={'verbose_name': 'Livro e Autor', 'verbose_name_plural': 'Livros e Autores'},
        ),
        migrations.AlterModelOptions(
            name='local_publicacao',
            options={'verbose_name': 'Local de Publicação', 'verbose_name_plural': 'Locais de Publicação'},
        ),
    ]
