# Generated by Django 5.1.5 on 2025-01-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_cdd_options_alter_editora_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
