# Generated by Django 5.1.5 on 2025-01-15 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_leitor_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='leitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.leitor'),
        ),
    ]
