# Generated by Django 5.1.5 on 2025-01-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_emprestimo_leitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='codigo_autor',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='ano',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.IntegerField(null=True),
        ),
    ]
