# Generated by Django 5.1.5 on 2025-01-16 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_alter_autor_codigo_autor_alter_livro_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livrotemautor',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores', to='biblioteca.autor'),
        ),
        migrations.AlterField(
            model_name='livrotemautor',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='biblioteca.livro'),
        ),
    ]
